Traceback (most recent call last):
  File "errorExample.py", line 10, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
